### ISSUE TITLE
Fails when run as cron task with `smbclient: command not found` message

### ISSUE THREAD

**Issue by SixBytesUnder** [eflexsystems/node-samba-client#31]
Hi

I have a Node script that works perfectly fine when I run it from the command line.
When I try to run it as a cron command with 
`*/15 * * * * cd /home/path/to/local/script && node index.js >> /home/path/to/my/log.log 2>&1`
I get the following error

```
Error: Command failed: smbclient -U 'myuser' -c 'dir "path\to\remote\"' {rest of sensitive info removed}
/bin/sh: smbclient: command not found
/bin/sh: smbclient: command not found

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:674:12) {
  killed: false,
  code: 127,
  signal: null,
  cmd: `smbclient -U 'myuser' -c 'dir "path\to\remote\"' {rest of sensitive info removed}`
}
```
When I manually run the full command given in the above last line, all works fine.
It's just when I run my script as a cron task. Any idea why it's failing?

Please note, I have other methods in this script that work just fine. It's just the `smbclient` that seems have issues.

**Comment by SixBytesUnder** [comment]
I've found a solution. Nothing to do with this package but rather a missing path scope in cron.

1. execute `echo $PATH` on your command line
2. copy the whole output
3. add this line at the very top of your crontab `PATH=\whatever\path\you\got\in\point 1`
